const data = {
  products: [
    {
      _id: "1",
      name: "Adidas Fit Shirt",
      category: "Shirt",
      image: "/images/product6.png",
      price: "130",
      countInStock: "10",
      brand: "Adidas",
      rating: "4.5",
      numReviews: "10",
      description: "high quality p description",
    },
    {
      _id: "2",
      name: "Nike Slim Shirt",
      category: "Shirt",
      image: "/images/product5.png",
      price: "120",
      countInStock: "10",
      brand: "Nike",
      rating: "4.0",
      numReviews: "10",
      description: "high quality p",
    },
    {
      _id: "3",
      name: "Lacoste free Shirt",
      category: "Shirt",
      image: "/images/product4.png",
      price: "150",
      countInStock: "100",
      brand: "Lacoste",
      rating: "4.8",
      numReviews: "15",
      description: "high quality p",
    },
    {
      _id: "4",
      name: "Nike Slim Pant",
      category: "pants",
      image: "/images/product3.png",
      price: "130",
      countInStock: "50",
      brand: "Nike",
      rating: "4.5",
      numReviews: "10",
      description: "high quality p",
    },
    {
      _id: "5",
      name: "Puma Slim Pant",
      category: "Pants",
      image: "/images/product2.png",
      price: "65",
      countInStock: "30",
      brand: "Puma",
      rating: "4.5",
      numReviews: "20",
      description: "high quality p",
    },
    {
      _id: "6",
      name: "Adidas Fit Pant",
      category: "pant",
      image: "/images/product1.png",
      price: "120",
      countInStock: "12",
      brand: "Adidas",
      rating: "4.5",
      numReviews: "100",
      description: "high quality p",
    },
  ],
};
export default data;
